import {test,expect,type Page} from '@playwright/test'
import {initial,KEY,apply} from '../src/domain'
async function open(p:Page){await p.goto('./')}
async function correct(p:Page){await p.getByRole('button',{name:'Inspect missing item A02'}).click();await p.getByRole('button',{name:'Edit controlled tags'}).click();await p.getByRole('checkbox',{name:'bicycle',exact:true}).check();await p.getByRole('button',{name:'Preview tag change'}).click()}
async function confirm(p:Page){await p.getByRole('button',{name:'Confirm change'}).click()}
async function closeDrawer(p:Page){await p.getByRole('button',{name:'Close metadata'}).click()}
test('primary tag correction explains actual fields and fixed before/after arithmetic',async({page})=>{await open(page);await expect(page.getByRole('status').first()).toContainText('2 of 6');await correct(page);await expect(page.getByRole('dialog')).toContainText('Only record A02');await expect(page.getByRole('dialog')).toContainText('2 → 3');await confirm(page);await expect(page.getByRole('button',{name:'Edit controlled tags'})).toBeFocused();await expect(page.getByLabel('Asset metadata')).toContainText('bicycle: tags');await closeDrawer(page);await expect(page.getByRole('status').first()).toContainText('3 of 6');await page.getByRole('button',{name:'Compare query fixtures'}).click();await expect(page.locator('tbody tr').first()).toContainText('1/2 → 2/3');await expect(page.locator('tbody tr').first()).toContainText('1/2 → 0/2')})
test('compatible refresh restores edits and preserved history',async({page})=>{await open(page);await correct(page);await confirm(page);await page.reload();await expect(page.getByRole('status').first()).toContainText('3 of 6');await page.getByRole('button',{name:'Inspect missing item A02'}).click();await expect(page.getByLabel('Asset metadata')).toContainText('revision 1');await expect(page.getByLabel('Asset metadata')).toContainText('Original tags: commute, urban')})
test('cancel preview and cancel tag editor write nothing',async({page})=>{await open(page);await correct(page);await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.getByRole('button',{name:'Preview tag change'})).toBeFocused();await page.getByRole('button',{name:'Cancel tag edit'}).click();expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBeNull()})
test('facet exclusion clear and reversible view restoration',async({page})=>{await open(page);await page.getByLabel('Asset type').selectOption('Poster');await expect(page.getByText('The query matches assets, but active facets exclude every match.')).toBeVisible();await page.getByRole('button',{name:'Clear facets'}).click();await expect(page.getByRole('status').first()).toContainText('2 of 6');await page.getByRole('button',{name:'Restore previous view'}).click();await expect(page.getByLabel('Asset type')).toHaveValue('Poster')})
test('query mismatch recovery does not misattribute exclusion',async({page})=>{await open(page);await page.getByLabel('Search the collection').fill('meteor');await expect(page.getByText('No record matches every query token in this scope.',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Clear query'}).click();await expect(page.getByRole('status').first()).toContainText('6 of 6');await page.getByRole('button',{name:'Restore previous view'}).click();await expect(page.getByLabel('Search the collection')).toHaveValue('meteor')})
test('scope title vs tags and transparent directional policy',async({page})=>{await open(page);await page.getByLabel('Search the collection').fill('bike');await page.getByRole('button',{name:'Review synonym policy'}).click();await expect(page.getByRole('dialog')).toContainText('no synonym expansion');await confirm(page);await expect(page.getByRole('status').first()).toContainText('0 of 6');await page.getByRole('button',{name:'Compare query fixtures'}).click();await expect(page.locator('tbody tr').nth(1)).toContainText('0/0 (undefined)');await expect(page.locator('tbody tr').nth(1)).toContainText('2/2')})
test('Undo restores only latest metadata edit and appends history',async({page})=>{await open(page);await correct(page);await confirm(page);await closeDrawer(page);await page.getByRole('button',{name:'Review synonym policy'}).click();await confirm(page);await page.getByRole('button',{name:'Review Undo latest edit'}).click();await confirm(page);await page.getByRole('button',{name:'Inspect missing item A02'}).click();await expect(page.getByLabel('Asset metadata')).toContainText('Current controlled tags');const s=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!),KEY);expect(s.tags.A02).toEqual(['commute','urban','bicycle']);expect(s.synonyms).toBe(true);expect(s.history).toHaveLength(3)})
test('invalid saved data remains until reviewed reset',async({page})=>{await page.addInitScript(k=>localStorage.setItem(k,'{corrupt'),KEY);await open(page);await expect(page.getByRole('alert')).toContainText('preserved');await page.getByRole('button',{name:'Review reset sample'}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBe('{corrupt');await page.getByRole('button',{name:'Review reset sample'}).click();await confirm(page);await expect(page.getByRole('alert')).toHaveCount(0);expect(JSON.parse((await page.evaluate(k=>localStorage.getItem(k),KEY))!).revision).toBe(0)})
test('corruption introduced after load is preserved and reset reachable',async({page})=>{await open(page);await page.evaluate(k=>localStorage.setItem(k,'broken'),KEY);await correct(page);await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('alert')).toContainText('invalid');await closeDrawer(page);await page.getByRole('button',{name:'Review reset sample'}).click();await confirm(page);expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).revision,KEY)).toBe(0)})
test('stale preview rejects same-revision changed saved bytes',async({page})=>{await page.addInitScript(([k,s])=>localStorage.setItem(k,s),[KEY,JSON.stringify(initial())]);await open(page);await correct(page);await page.evaluate(k=>{const s=localStorage.getItem(k)!;localStorage.setItem(k,' '+s)},KEY);await confirm(page);await expect(page.getByRole('status').nth(1)).toContainText('stale');expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).revision,KEY)).toBe(0)})
test('stale preview detects corruption during review',async({page})=>{await open(page);await correct(page);await page.evaluate(k=>localStorage.setItem(k,'corrupt'),KEY);await confirm(page);await expect(page.getByRole('alert')).toContainText('invalid');expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBe('corrupt')})
test('external valid changes before preview block overwriting unrelated edits',async({page})=>{await open(page);const s=apply(initial(),{kind:'policy',before:true,after:false});await page.evaluate(([k,s])=>localStorage.setItem(k,s),[KEY,JSON.stringify(s)]);await correct(page);await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('status').nth(1)).toContainText('another context');expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)!).synonyms,KEY)).toBe(false)})
test('selection context invalidates tag preview',async({page})=>{await open(page);await correct(page);await page.getByRole('button',{name:'Inspect Bicycle route study'}).evaluate((e:HTMLElement)=>e.click());await confirm(page);await expect(page.getByRole('status').nth(1)).toContainText('stale');expect(await page.evaluate(k=>localStorage.getItem(k),KEY)).toBeNull()})
for(const mode of ['getter','getItem','setItem'])test(`${mode} failure keeps memory with warning`,async({page})=>{await page.addInitScript(mode=>{if(mode==='getter')Object.defineProperty(window,'localStorage',{get(){throw Error('unavailable')}});else Object.defineProperty(Storage.prototype,mode,{value(){throw Error('unavailable')}})},mode);await open(page);await correct(page);await confirm(page);await expect(page.getByRole('alert')).toContainText('Storage unavailable');await closeDrawer(page);await expect(page.getByRole('status').first()).toContainText('3 of 6')})
test('keyboard Tab Shift+Tab Escape and focus restoration',async({page})=>{await open(page);await page.getByLabel('Search the collection').focus();await page.keyboard.press('Tab');await expect(page.getByLabel('Search scope')).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(page.getByLabel('Search the collection')).toBeFocused();await page.getByRole('button',{name:'Inspect Bicycle route study'}).click();await expect(page.getByLabel('Asset metadata')).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Inspect Bicycle route study'})).toBeFocused();await page.getByRole('button',{name:'Review synonym policy'}).click();await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();await page.keyboard.press('Shift+Tab');await expect(page.getByRole('button',{name:'Confirm change'})).toBeFocused();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Review synonym policy'})).toBeFocused()})
for(const width of [320,390])test(`mobile ${width} primary flow without horizontal document overflow`,async({page})=>{await page.setViewportSize({width,height:740});await open(page);await correct(page);await expect(page.getByRole('button',{name:'Confirm change'})).toBeInViewport();await confirm(page);await closeDrawer(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`evidence/mobile-${width}.png`,fullPage:true})})
test('desktop revealed controls visible with clean console and local-only app requests',async({page})=>{const errors:string[]=[];const external:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4190'))external.push(r.url())});await open(page);await page.screenshot({path:'evidence/desktop.png',fullPage:true});await page.getByRole('button',{name:'Inspect missing item A02'}).click();await expect(page.getByRole('button',{name:'Close metadata'})).toBeInViewport();await page.getByRole('button',{name:'Edit controlled tags'}).click();await expect(page.getByRole('checkbox',{name:'bicycle',exact:true})).toBeInViewport();await page.getByRole('checkbox',{name:'bicycle',exact:true}).check();await page.getByRole('button',{name:'Preview tag change'}).click();await expect(page.getByRole('button',{name:'Confirm change'})).toBeInViewport();await page.screenshot({path:'evidence/preview.png'});expect(errors).toEqual([]);expect(external).toEqual([])})
